/*******************************************************************************
 *    Copyright (C) Cambridge Silicon Radio Limited 2016
 *
 * FILE
 *    hid_descriptor.h
 *
 *  DESCRIPTION
 *    This file defines the HID descriptor for this remote control.
 *
 * == THIS FILE IS AUTO-GENERATED BY THE REMOTE CONTROL GENERATOR APPLICATION. ==
 *    Any changes made here will be lost if the generator application is re-run.
 *
 *    This file was generated on 21/Oct/2016 at 01:29:49 (GMT),
 *    using app version v150223.6448.
 *
 ******************************************************************************/
#define DECLARE_HID_DESCRIPTOR()	\
static uint8 hidDescriptor[] = \
{\
             0x05, 0x0c,        /* Usage page (Consumer Devices) */\
             0x09, 0x01,        /* Usage (Consumer Control) */\
             0xa1, 0x01,        /* Collection (Application) */\
             0x85, 0x01,        /*   Report ID (1) */\
             0x19, 0x00,        /*   Usage Minimum (0) */\
             0x2A, 0x9c, 0x02,  /*   Usage Maximum (29c) */\
             0x15, 0x00,        /*   Logical Minimum (0) */\
             0x26, 0x9c, 0x02,  /*   Logical Maximum (29c) */\
             0x95, 0x01,        /*   Report Count (1) */\
             0x75, 0x10,        /*   Report Size (16) */\
             0x81, 0x00,        /*   Input (Data,Ary,Abs) */\
             0xC0\
}
